package pages;

import org.openqa.selenium.By;

public class MailinatorRepo {
	public By mailBox=By.xpath("//input[@id='search']");
	public By clickMail=By.xpath("//button[text()='GO']");
	public By eduleyApprovedMail=By.xpath("//td[contains(text(),'Your account is approved and ready to use')]");
	public By givenEmail=By.xpath("//li[contains(text(),'Email')]");
	public By autoGeneratedPassword=By.xpath("//li[contains(text(),'Password')]");
	public By resetPasswordMail=By.xpath("//td[contains(text(),'Reset')]");
	public By resetPassword=By.xpath("//a[text()='Reset Password']");
	public By resetPasswordConfirm=By.xpath("//a[text()=' CONFIRM ']");

	
	

}
