package pages;

import java.util.Set;

import org.openqa.selenium.By;
import org.openqa.selenium.ElementClickInterceptedException;
import org.openqa.selenium.Keys;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.WebDriver;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import constants.Constants;
import utilities.LocalHelper;
import utilities.TestUtil;

public class YopMail extends YopMailRepo{
	public static String userLoginMail;
	public static String userLoginPassword;
	protected static final Logger logger = LoggerFactory.getLogger(YopMail.class);

	private final LocalHelper localHelper = new LocalHelper();

	private final WebDriver driver;
	public YopMail(WebDriver driver) {
		this.driver=driver;
	}
	public void launchYopMail(WebDriver driver) {
		driver.get(Constants.yopmail);
	}
	
	
	
	public void enterEmail(String email) {
		localHelper.sendKeys(mailNameBox,email,driver);
		localHelper.clickElement(clickMail,driver);
	}
	public void switchToFrameYopMail(WebDriver driver) {
		driver.switchTo().frame("ifmail");
	}	
	public void getMailAndPassword() {
		userLoginMail=localHelper.getTextButSplitBySpace(givenEmail,driver);
		 userLoginPassword=localHelper.getTextButSplitBySpace(autoGeneratedPassword,driver);
	}
	public void clickLoginToAdminPortal() {
		try {
			localHelper.clickElement(loginToAdminPanel, driver);
		}catch (ElementClickInterceptedException m) {
			localHelper.jsExecutorClick(loginToAdminPanel, driver);
		}
		logger.info("User Login to Admin portal is clicked");
	}
public void switchToNewAdminPortalWindow(WebDriver driver) {
		
		String windowHandle = driver.getWindowHandle();
		Set<String> windowHandles = driver.getWindowHandles();
		for (String string : windowHandles) {
			if(!string.contains(windowHandle)) {
				driver.switchTo().window(string);
			}
		}
		logger.info("Switched to new window");
	}
public void enterAdminPanelUserName() throws InterruptedException {
	try {
		localHelper.clickElement(adminPanelUsernameBox, driver);
	localHelper.sendKeys(adminPanelUsernameBox,userLoginMail,driver);
//	localHelper.clickElement(adminPanelPasswordBox, driver);
	}catch (StaleElementReferenceException e) {
		localHelper.sendKeys(adminPanelUsernameBox,userLoginMail,driver);
		//localHelper.clickElement(adminPanelPasswordBox, driver);
	}
	logger.info("UserName passed in the Admin panel Username box");
}
public void enterAdminPanelPassword() {
	localHelper.jsExecutorHighlight(adminPanelPasswordBox, driver);
	localHelper.sendKeys(adminPanelPasswordBox,userLoginPassword,driver);
	logger.info("Password passed in the Admin panel Password box");
}
public void clickLoginButton() {
	try {
		localHelper.jsExecutorHighlight(adminPanelLogin, driver);
		localHelper.clickElement(adminPanelLogin, driver);
	}catch (ElementClickInterceptedException m) {
		localHelper.jsExecutorClick(adminPanelLogin, driver);
	}
	logger.info("Admin panel login button is clicked");
}
public void switchToParentWindow(WebDriver driver) {
	String windowHandle = driver.getWindowHandle();
	Set<String> windowHandles = driver.getWindowHandles();
	
	driver.switchTo().window(driver.getWindowHandles().toArray()[0].toString());
	logger.info("Switched to parent window");
	
	}

public void clickViewStudentHomePage() throws InterruptedException {
	try {
		localHelper.clickElement(viewStudentHomePage, driver);
	}catch (ElementClickInterceptedException m) {
		localHelper.jsExecutorClick(viewStudentHomePage, driver);
	}
	logger.info("User clicked on view student home page");
}
public void clickCourseEditButton() throws InterruptedException {
	try {
		localHelper.clickElement(courseEditButton, driver);
	}catch (ElementClickInterceptedException m) {
		localHelper.jsExecutorClick(courseEditButton, driver);
	}
	logger.info("User clicked on Course edit button");
}
public void clickFreeCourseCheckbox() {
	driver.findElement(By.xpath("//input[@type='checkbox']")).sendKeys(Keys.SPACE);

		//localHelper.clickElement(freeCourseCheckBox, driver);
	}
public void SelectCourseStatusLive() throws InterruptedException {
	try {
		localHelper.clickElement(courseStatusDropdown, driver);
		localHelper.clickElement(courseStatusLive, driver);
	}catch (ElementClickInterceptedException m) {
		localHelper.jsExecutorClick(courseStatusDropdown, driver);
		localHelper.jsExecutorClick(courseStatusLive, driver);
	}
	logger.info("User selected on Course status Live ");
}
public void clickCourseStatusSubmitButton() throws InterruptedException {
	Thread.sleep(3000);
	try {
		localHelper.clickElement(courseStatusSubmitButton, driver);
	}catch (ElementClickInterceptedException m) {
		localHelper.jsExecutorClick(courseStatusSubmitButton, driver);
	}
	logger.info("User clicked on Course status submit button");
}


public void clickResetButton() throws InterruptedException {
	try {
		localHelper.clickElement(resetPassword, driver);
	}catch (ElementClickInterceptedException m) {
		localHelper.jsExecutorClick(resetPassword, driver);
	}
	logger.info("User clicked on Reset button");
}



	
}	
