package pages;

import org.openqa.selenium.By;

public class YopMailRepo {
	public By mailNameBox=By.xpath("//input[@id='login']");
	public By clickMail=By.xpath("//button[@class='md']");
	public By firstMail=By.xpath("//span[text()='Spend The Bits']");
	public By setPassword=By.xpath("//a[text()='Set Password']");
	public By newPassword=By.xpath("//input[@id='password']");
	public By confirmPassword=By.xpath("//input[@id='confirmpassword']");
	public By changePasswordButton=By.xpath("//button[text()='Change Password']");
	public By successToastMessage=By.xpath("//div[text()='Congratulations, your password has been successfully updated']");
	public By checkMailBox=By.xpath("//button[text()='Check the mail!']");
	public By signInButton=By.xpath("//button[text()='Sign In']");
	public By givenEmail=By.xpath("//li[contains(text(),'Email:')]");
	public By autoGeneratedPassword=By.xpath("//li[contains(text(),'Password:')]");
	public By loginToAdminPanel=By.xpath("//a[contains(text(),'Login to Admin Panel')]");
	public By viewStudentHomePage=By.xpath("//a[contains(text(),'View Student Homepage')]");
	public By adminPanelUsernameBox=By.xpath("//input[@name='email']");
	public By adminPanelPasswordBox=By.xpath("//input[@name='password']");
	public By adminPanelLogin=By.xpath("//button[text()='Login']");
	public By courseEditButton=By.xpath("//button[@aria-label='edit']");
	public By courseStatusDropdown=By.xpath("//div[@aria-haspopup='listbox']//parent::div[@class='MuiOutlinedInput-root MuiInputBase-root MuiInputBase-colorPrimary MuiInputBase-fullWidth css-s76avs']");
	public By freeCourseCheckBox=By.xpath("//input[@type='checkbox']");
	public By courseStatusLive=By.xpath("//li[text()='Live']");
	public By courseStatusSubmitButton=By.xpath("//button[text()='Submit']");
	
	public By resetPassword=By.xpath("//a[text()='Reset Password']");
	
	
	

}
